title: "Oscar Reyes Umanzor"
description: "Cybersecurity • Networking • Data Systems"
url: "https://kingtechs.github.io"   # your GitHub Pages domain
baseurl: "/Kingtechs"                # because your site URL has /Kingtechs/

remote_theme: LeNPaul/Millennial

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
